require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ApplicationFormsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ApplicationForm. As you add validations to ApplicationForm, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ApplicationFormsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all application_forms as @application_forms" do
      application_form = ApplicationForm.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:application_forms)).to eq([application_form])
    end
  end

  describe "GET show" do
    it "assigns the requested application_form as @application_form" do
      application_form = ApplicationForm.create! valid_attributes
      get :show, {:id => application_form.to_param}, valid_session
      expect(assigns(:application_form)).to eq(application_form)
    end
  end

  describe "GET new" do
    it "assigns a new application_form as @application_form" do
      get :new, {}, valid_session
      expect(assigns(:application_form)).to be_a_new(ApplicationForm)
    end
  end

  describe "GET edit" do
    it "assigns the requested application_form as @application_form" do
      application_form = ApplicationForm.create! valid_attributes
      get :edit, {:id => application_form.to_param}, valid_session
      expect(assigns(:application_form)).to eq(application_form)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ApplicationForm" do
        expect {
          post :create, {:application_form => valid_attributes}, valid_session
        }.to change(ApplicationForm, :count).by(1)
      end

      it "assigns a newly created application_form as @application_form" do
        post :create, {:application_form => valid_attributes}, valid_session
        expect(assigns(:application_form)).to be_a(ApplicationForm)
        expect(assigns(:application_form)).to be_persisted
      end

      it "redirects to the created application_form" do
        post :create, {:application_form => valid_attributes}, valid_session
        expect(response).to redirect_to(ApplicationForm.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved application_form as @application_form" do
        post :create, {:application_form => invalid_attributes}, valid_session
        expect(assigns(:application_form)).to be_a_new(ApplicationForm)
      end

      it "re-renders the 'new' template" do
        post :create, {:application_form => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested application_form" do
        application_form = ApplicationForm.create! valid_attributes
        put :update, {:id => application_form.to_param, :application_form => new_attributes}, valid_session
        application_form.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested application_form as @application_form" do
        application_form = ApplicationForm.create! valid_attributes
        put :update, {:id => application_form.to_param, :application_form => valid_attributes}, valid_session
        expect(assigns(:application_form)).to eq(application_form)
      end

      it "redirects to the application_form" do
        application_form = ApplicationForm.create! valid_attributes
        put :update, {:id => application_form.to_param, :application_form => valid_attributes}, valid_session
        expect(response).to redirect_to(application_form)
      end
    end

    describe "with invalid params" do
      it "assigns the application_form as @application_form" do
        application_form = ApplicationForm.create! valid_attributes
        put :update, {:id => application_form.to_param, :application_form => invalid_attributes}, valid_session
        expect(assigns(:application_form)).to eq(application_form)
      end

      it "re-renders the 'edit' template" do
        application_form = ApplicationForm.create! valid_attributes
        put :update, {:id => application_form.to_param, :application_form => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested application_form" do
      application_form = ApplicationForm.create! valid_attributes
      expect {
        delete :destroy, {:id => application_form.to_param}, valid_session
      }.to change(ApplicationForm, :count).by(-1)
    end

    it "redirects to the application_forms list" do
      application_form = ApplicationForm.create! valid_attributes
      delete :destroy, {:id => application_form.to_param}, valid_session
      expect(response).to redirect_to(application_forms_url)
    end
  end

end
